# Generated by Django 4.0.6 on 2022-07-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addinformation',
            name='idname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.udname'),
        ),
        migrations.AddField(
            model_name='addinformation1',
            name='idname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.udname'),
        ),
    ]
