# Generated by Django 4.0.6 on 2022-07-17 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_addinformation_idname_addinformation1_idname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addinformation',
            name='idname',
        ),
        migrations.RemoveField(
            model_name='addinformation1',
            name='idname',
        ),
        migrations.DeleteModel(
            name='UdName',
        ),
    ]
