# Generated by Django 3.2.14 on 2022-08-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_addinformation_idname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproject',
            name='body',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
