# Generated by Django 3.2.14 on 2022-08-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220809_0541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddInformation',
        ),
        migrations.DeleteModel(
            name='AddInformation1',
        ),
    ]
